theme: jekyll-theme-architect

# Setup
name:         Hello Toitoi
tagline:      soemtihng bauot me
baseurl:      ""
locale:       "en"

title: 503mt1hn8 b4u07 m3
description: [A short description of your site's purpose]
